"""
scrape_fotmob.py

Purpose
-------
Pull match-level, shot-based xG for an EFL division (Championship,
League One, or League Two — pick with --league) from FotMob.

Background: FotMob's raw JSON API now requires a client-generated signed
header ("X-Fm-Req") that a plain Python script can't easily reproduce
(it's regenerated by their frontend JS and has broken third-party tools
before — see https://viktornilsson.github.io/security/2024/11/01/fotmob-auth.html).

BUT FotMob's actual match web pages (https://www.fotmob.com/match/<id>)
still embed the full match data — including the "Expected goals (xG)"
stat — as a plain JSON blob inside a <script id="__NEXT_DATA__"> tag in
the page's HTML. No token needed to read that. This script uses that
route: fetch the page, pull out the embedded JSON, search it for the
match list and the xG stat, rather than calling the API directly.

This is still an UNOFFICIAL, undocumented data path. FotMob can change
their page structure at any time, which would break the JSON-path
lookups here. The script searches the embedded JSON structurally
(looking for the shapes of things, e.g. "a list of dicts that look like
matches") rather than hardcoding one exact path, to be a bit more
resilient to minor changes — but this is best-effort, not guaranteed.

Output schema matches scrape_fbref.py's output exactly, so build_deltas.py
works unchanged:
    date, home_team, away_team, home_xg, away_xg, home_goals, away_goals

Usage
-----
    python scrape_fotmob.py --league league-one --output data/fotmob_league-one_xg.csv

    # Optionally limit to matches after a given date (faster reruns):
    python scrape_fotmob.py --league league-two --output data/fotmob_league-two_xg.csv --since 2026-08-01

Rate limiting
-------------
This script fetches one page per match, which is a lot of requests for a
full season (~500+ matches). It sleeps between requests by default —
don't remove that, or you risk getting temporarily blocked. Consider
running it in batches (e.g. once a week for that week's new matches)
using --since, rather than re-fetching the whole season every time.

FotMob league IDs/slugs (see leagues.py): Championship=48/"championship",
League One=108/"league-one", League Two=109/"league-two". FotMob's match
pages do carry an xG stat for League One and League Two, not just the
Championship, so this script works unchanged across all three divisions
— only the league id/slug (and hence which schedule page gets fetched)
changes.
"""

import argparse
import json
import re
import time
from datetime import datetime
from pathlib import Path

import pandas as pd
import requests

from leagues import get_league

HEADERS = {
    "User-Agent": (
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
        "(KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"
    ),
    "Accept-Language": "en-GB,en;q=0.9",
}
REQUEST_DELAY_SECONDS = 3


def fetch_next_data(url: str) -> dict:
    """Fetch a FotMob page and extract the embedded __NEXT_DATA__ JSON blob."""
    resp = requests.get(url, headers=HEADERS, timeout=30)
    resp.raise_for_status()
    match = re.search(
        r'<script id="__NEXT_DATA__" type="application/json">(.*?)</script>',
        resp.text, re.DOTALL
    )
    if not match:
        raise ValueError(
            f"Could not find __NEXT_DATA__ block on {url}. "
            f"FotMob may have changed their page structure, or this "
            f"request was blocked/redirected (check resp.status_code "
            f"and resp.text manually if this keeps happening)."
        )
    return json.loads(match.group(1))


def find_lists_of_dicts(obj, path=""):
    """Recursively walk a JSON structure, yielding (path, list) for every
    list whose items are dicts. Used to structurally search for the match
    list and stats list without hardcoding an exact path."""
    if isinstance(obj, dict):
        for k, v in obj.items():
            yield from find_lists_of_dicts(v, f"{path}.{k}")
    elif isinstance(obj, list):
        if obj and all(isinstance(item, dict) for item in obj):
            yield path, obj
        for i, item in enumerate(obj):
            yield from find_lists_of_dicts(item, f"{path}[{i}]")


def find_match_list(next_data: dict):
    """Search the embedded JSON for a list of dicts that look like
    fixtures (have recognisable home/away team info)."""
    candidates = []
    for path, lst in find_lists_of_dicts(next_data):
        sample = lst[0]
        keys = set(sample.keys())
        # Heuristic: fixture entries typically have some combination of
        # these keys across FotMob's various page layouts.
        looks_like_match = (
            {"home", "away"} <= keys or
            {"homeTeam", "awayTeam"} <= keys or
            ("home" in keys and "id" in keys and "status" in keys)
        )
        if looks_like_match:
            candidates.append((path, lst))
    # Prefer the longest matching list (most likely the full fixture list,
    # not a small "related matches" widget)
    candidates.sort(key=lambda c: len(c[1]), reverse=True)
    return candidates[0][1] if candidates else None


def extract_xg_from_html(html: str):
    """Extract the match's xG from the page's rendered text.

    FotMob's match page renders a "Top stats" section as plain visible
    HTML (not hidden in JSON) with the pattern:
        Expected goals (xG)
        <home value>
        <away value>
    This strips tags to plain text and regex-matches that pattern
    directly, which is simpler and more robust than trying to find the
    right path inside the embedded __NEXT_DATA__ JSON (whose exact
    structure varies and is harder to pin down reliably).
    """
    text = re.sub(r"<[^>]+>", " ", html)
    text = re.sub(r"\s+", " ", text)

    match = re.search(
        r"Expected goals \(xG\)\s*([\d]+\.?[\d]*)\s*([\d]+\.?[\d]*)",
        text
    )
    if not match:
        return None, None
    return float(match.group(1)), float(match.group(2))


def get_match_ids_and_meta(since: str | None, league_id: int, league_slug: str, league_label: str):
    """Fetch the given league's schedule page and extract match id, date,
    home/away team names, scores, and finished status."""
    url = f"https://www.fotmob.com/leagues/{league_id}/matches/{league_slug}"
    next_data = fetch_next_data(url)
    time.sleep(REQUEST_DELAY_SECONDS)

    match_list = find_match_list(next_data)
    if not match_list:
        raise ValueError(
            f"Could not locate a match list in the {league_label} schedule "
            "page's embedded JSON. FotMob may have changed their page "
            "layout — this script will need updating."
        )

    matches = []
    for m in match_list:
        match_id = m.get("id") or m.get("matchId")
        status = m.get("status", {})
        is_finished = (
            status.get("finished") is True
            or str(status.get("shortStatus", "")).upper() == "FT"
        )
        if not match_id or not is_finished:
            continue

        # Team names and scores show up under different keys depending on page layout
        home_name = (m.get("home") or {}).get("name") or m.get("homeTeam", {}).get("name")
        away_name = (m.get("away") or {}).get("name") or m.get("awayTeam", {}).get("name")
        home_goals = (m.get("home") or {}).get("score")
        away_goals = (m.get("away") or {}).get("score")
        date_str = m.get("status", {}).get("utcTime") or m.get("time")

        if since and date_str:
            try:
                match_date = datetime.fromisoformat(date_str.replace("Z", "+00:00")).date()
                if match_date < datetime.fromisoformat(since).date():
                    continue
            except ValueError:
                pass  # if date parsing fails, just include the match rather than skip it

        matches.append({
            "match_id": match_id,
            "date": date_str,
            "home_team": home_name,
            "away_team": away_name,
            "home_goals": home_goals,
            "away_goals": away_goals,
        })

    return matches


def get_match_xg(match_id) -> tuple:
    url = f"https://www.fotmob.com/match/{match_id}"
    resp = requests.get(url, headers=HEADERS, timeout=30)
    resp.raise_for_status()
    return extract_xg_from_html(resp.text)


def main(output_path, since, league_key):
    league = get_league(league_key)
    print(f"Fetching {league['label']} schedule...")
    matches = get_match_ids_and_meta(
        since, league["fotmob_id"], league["fotmob_slug"], league["label"]
    )
    print(f"Found {len(matches)} finished matches to process.")

    rows = []
    for i, m in enumerate(matches):
        print(f"[{i + 1}/{len(matches)}] {m['home_team']} vs {m['away_team']} (id {m['match_id']})")
        try:
            home_xg, away_xg = get_match_xg(m["match_id"])
            if home_xg is None or away_xg is None:
                print(f"  -> Could not find xG for this match, skipping.")
                continue
            rows.append({
                "date": m["date"],
                "home_team": m["home_team"],
                "away_team": m["away_team"],
                "home_xg": home_xg,
                "away_xg": away_xg,
                "home_goals": m["home_goals"],
                "away_goals": m["away_goals"],
            })
        except Exception as e:
            print(f"  -> Error: {e}")
        time.sleep(REQUEST_DELAY_SECONDS)

    new_df = pd.DataFrame(rows)

    # When --since is used for a fast weekly rerun, this run only covers
    # recent matches — merge onto whatever's already in output_path instead
    # of overwriting it, or every earlier match's xG would be lost.
    existing_path = Path(output_path)
    if since and existing_path.exists():
        existing_df = pd.read_csv(existing_path)
        combined = pd.concat([existing_df, new_df], ignore_index=True)
        combined = combined.drop_duplicates(
            subset=["date", "home_team", "away_team"], keep="last"
        )
        df = combined.sort_values("date").reset_index(drop=True)
    else:
        df = new_df

    df.to_csv(output_path, index=False)
    print(f"\nWrote {len(df)} total matches with xG to {output_path} "
          f"({len(new_df)} fetched this run)")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--league", default="championship",
                         choices=["championship", "league-one", "league-two"])
    parser.add_argument("--output", required=True)
    parser.add_argument("--since", default=None,
                         help="Only include matches on/after this date (YYYY-MM-DD)")
    args = parser.parse_args()

    main(args.output, args.since, args.league)
